webapp/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static
from . import views
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

handler404 = 'app.views.error_404'
handler500 = 'app.views.error_500'


urlpatterns = [

    path('subscription/', include('subscription.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path("login", views.signin, name="login"),
    path("logout", views.signout, name="logout"),
    path('admin/', admin.site.urls),
]

# since the only application is going to be the subscription application
# redirect the root of the site to the subscriptions app
urlpatterns += [
    path('', RedirectView.as_view(url='subscription/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# one time script to create product in stripe / thought middleware here would be overkill
# get plan from stripe
try:
    stripe.Plan.retrieve(settings.PLAN_ID)
except:
    # create plan using configuration setting in app
    plan = stripe.Plan.create(
        amount=settings.AMOUNT,
        currency=settings.CURRENCY,
        interval=settings.INTERVAL,
        trial_period_days=settings.TRIAL_PERIOD_DAYS,
        product={"name": settings.PRODUCT_NAME},
    )
    # set PLAN_ID in settings
    settings.PLAN_ID = plan.id

webapp/subscription/urls.py
from django.urls import path
# import views for subscription
from . import views

# define application name space
app_name = 'subscription'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('account', views.account, name='acount'),
    path('subscribe/<str:id>', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:id>', views.unsubscribe, name='unsubscribe')
]

webapp/subscription/models.py
# import timezone field to set subscription
# dates (creation, update and so on)
from django.utils import timezone
# import base django models to inherit
# and create a subscription class from
from django.db import models
# import base django user model to set as
# a foreign key for user
from django.contrib.auth.models import User

# Create your models here.


class Subscription(models.Model):
    # subscription ID to be used to mange subscription / generated by stripe
    stripe_id = models.CharField(max_length=200, null=False)
    # status of subscription
    status = models.CharField(max_length=200, null=False, default='trialing')
    # every subscription has a user
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=False, default=None)

webapp/subscription/views.py
from datetime import datetime
# for template rendering
from django.shortcuts import render, redirect
# to get stripe settings from app settings
from django.conf import settings
# to secure routes with login
from django.contrib.auth.decorators import login_required
# to allow only specific http methods on certain routes (like post only for e.g)
from django.views.decorators.http import require_http_methods
# to show alerts to user
from django.contrib import messages
# import subscription model
from subscription.models import Subscription
# import stripe
import stripe
from datetime import datetime, date

# set stripe api-key from settings
stripe.api_key = settings.STRIPE_SECRET_KEY


def landing(request):
    '''landing page where user either signs in or signs out'''
    return render(request, 'landing.html')

# require login
@login_required(login_url='/login')
def account(request):
    # get subscription in database
    subscription = Subscription.objects.filter(
        user=request.user).first()
    # create context variable to pass to template
    context = {'status': subscription.status,
               'stripe_id': subscription.stripe_id}
    # render template
    return render(request, 'account.html', context=context)

# require login
@login_required(login_url='/login')
def subscribe(request, id):
    # get subscription in database
    subscription = Subscription.objects.filter(stripe_id=id).first()
    # get subscription from stripe
    response = stripe.Subscription.retrieve(
        subscription.stripe_id)
    # update stripe
    response = stripe.Subscription.modify(
        response.id,
        cancel_at_period_end=False,
        proration_behavior='create_prorations',
        items=[{
            'id': response['items']['data'][0].id,
            'plan': response['items']['data'][0].plan['id']
        }]
    )
    # this is update step for local db
    subscription.status = response['status']
    # save changes in db
    subscription.save()
    # alert user
    messages.error(request, "Subscribed to premium.")
    # render cms
    return redirect('/subscription/account')


@login_required(login_url='/login')
def unsubscribe(request, id):
    # get subscription in database using stripe_id
    subscription = Subscription.objects.filter(stripe_id=id).first()
    # check status and modify stripe subscription accordingly
    if subscription.status == 'trialing':
        # get subscription from stripe and update
        response = stripe.Subscription.modify(
            subscription.stripe_id, cancel_at_period_end=True, trial_end='now')
        # this is update step for local db
        subscription.status = response['status']
        # save changes in db
        subscription.save()
        # alert user
        messages.error(request, "Unsubscribed from trial.")
        # render cms
        return redirect('/subscription/account')
    elif subscription.status == 'active':
        # get subscription from stripe and update
        response = stripe.Subscription.modify(
            subscription.stripe_id, cancel_at_period_end=True)
        # this is update step for local db
        subscription.status = 'canceled'
        # save changes in db
        subscription.save()
        # alert user
        messages.error(request, "Unsubscribed from premium.")
        # render cms
        return redirect('/subscription/account')

webapp/subscription/templates/account.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block content %}

<div class="card text-center">
  <div class="card-header">
    <div class="row">
      <div class="col-1">
        <a class="btn btn-sm" href="/logout" role="button">Log Out</a>
      </div>
      <div class="col-11">
        <h1 class="display-4">Account</h1>
      </div>
    </div>
  </div>
  <div class="card-body">
    <table class="table">
      <caption>
        List of subscriptions
      </caption>
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Account Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>WhatsBusy Premium</td>
          <td>{{status}}</td>
          <td>
            {% if status == 'canceled' %}
            <a
              class="btn btn-sm"
              href="{% url 'subscription:subscribe' stripe_id %}"
              role="button"
              >Subscribe</a
            >
            {% else %}
            <a
              class="btn btn-sm"
              href="{% url 'subscription:unsubscribe' stripe_id %}"
              role="button"
              >Unsubscribe</a
            >
            {% endif %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

webapp/subscription/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

    <title>Subscriptions</title>
  </head>
  <body>
    {% if messages %} {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{message}}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %} {% block content %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

webapp/subscription/templates/landing.html
{% extends 'base.html' %} {% block content %}

<div class="card text-center">
  <div class="card-header">
    <h1 class="display-4">WhatsBusy</h1>
  </div>
  <div class="card-body">
    <p class="lead">
      a simple subscriptions manager web app built using Django + Bootstrap +
      PostgreSQL
    </p>
    <hr class="my-4" />
    <p>
      built for WhatsBusy hackathon
    </p>
    <hr class="my-4" />
    <p class="lead">
      <a class="btn btn-lg" href="/login" role="button">Log In </a>
      <a class="btn btn-lg" href="/accounts/register" role="button">Register</a>
    </p>
  </div>
</div>
{% endblock %}